name: ulimit-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: | 
          curl -SL https://github.com/alexei-led/pumba/releases/download/0.7.2/pumba_linux_amd64 -O
          sudo mv pumba_linux_amd64 /usr/bin/pumba
          sudo chmod +x /usr/bin/pumba
          pumba --version
      - run: docker container run --name docker-nginx -d nginx
      - run: pumba stress -d 1m docker-nginx
      - run: ulimit -n
      - run: ulimit -u
      - run: ulimit -i
      - run: |
          paste <(grep 'open files\|processes\|pending signals' \
                        /proc/self/limits | cut -c27-38)        \
                <(i=`whoami`
                  lsof -n -u $i 2> /dev/null | 
                       tail -n +2 | 
                       awk {'print $9'} | 
                       wc -l
                  ps --no-headers -U $i -u $i u | wc -l
                  ps -u $i -o pid= | 
                       xargs printf "/proc/%s/status\n" |
                       xargs grep -s 'SigPnd' |
                       sed 's/.*\t//' | 
                       paste -sd+ | 
                       bc ; ) \
                <(grep 'open files\|processes\|pending signals' \
                       /proc/self/limits | 
                             cut -c1-19) | 
          while read a b name ; do 
              printf '%3i%%  %s\n' $((${b}00/a)) "$name"
          done
          
          
  build2:
    runs-on: ubuntu-latest

    steps:
      - run: ulimit -n
      - run: ulimit -u
      - run: ulimit -i
      - run: |
          paste <(grep 'open files\|processes\|pending signals' \
                        /proc/self/limits | cut -c27-38)        \
                <(i=`whoami`
                  lsof -n -u $i 2> /dev/null | 
                       tail -n +2 | 
                       awk {'print $9'} | 
                       wc -l
                  ps --no-headers -U $i -u $i u | wc -l
                  ps -u $i -o pid= | 
                       xargs printf "/proc/%s/status\n" |
                       xargs grep -s 'SigPnd' |
                       sed 's/.*\t//' | 
                       paste -sd+ | 
                       bc ; ) \
                <(grep 'open files\|processes\|pending signals' \
                       /proc/self/limits | 
                             cut -c1-19) | 
          while read a b name ; do 
              printf '%3i%%  %s\n' $((${b}00/a)) "$name"
          done
