name: ulimit-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: | 
          git clone https://github.com/javiroman/disk-stress.git
          cd disk-stress
          docker build . -t disk_filler
          # docker run  -d -p 8080:8080 --name filler disk_filler
          docker run  -d -p 8080:8080 --memory 1024m --cpuset-cpus=0 --name filler disk_filler 
          # curl -s 0.0.0.0:8080/fill?size=2
      - run: | 
          docker run --rm -d progrium/stress --cpu 2 --io 1 --vm 2 --vm-bytes 1G --timeout 20
          echo "test"
      # - run: docker container run --name docker-nginx -d nginx
      - run: sleep 1
      - run: ulimit -n
      - run: ulimit -u
      - run: ulimit -i
      - run: |
          paste <(grep 'open files\|processes\|pending signals' \
                        /proc/self/limits | cut -c27-38)        \
                <(i=`whoami`
                  lsof -n -u $i 2> /dev/null | 
                       tail -n +2 | 
                       awk {'print $9'} | 
                       wc -l
                  ps --no-headers -U $i -u $i u | wc -l
                  ps -u $i -o pid= | 
                       xargs printf "/proc/%s/status\n" |
                       xargs grep -s 'SigPnd' |
                       sed 's/.*\t//' | 
                       paste -sd+ | 
                       bc ; ) \
                <(grep 'open files\|processes\|pending signals' \
                       /proc/self/limits | 
                             cut -c1-19) | 
          while read a b name ; do 
              printf '%3i%%  %s\n' $((${b}00/a)) "$name"
          done
          
      - run: |
          # Based  on https://unix.stackexchange.com/questions/230346/how-to-check-ulimit-usage/288362

          paste <(grep 'open files\|processes\|pending signals' /proc/self/limits | cut -c27-38) \
                <(i=`whoami` ; lsof -n -u $i | tail -n +2 | awk {'print $9'} | wc -l; 
                               ps --no-headers -U $i -u $i u | wc -l ; 
                               ps -u $i -o pid= | xargs printf "/proc/%s/status\n" |
                                                  xargs grep -s 'SigPnd' |
                                                  sed 's/.*\t//' | paste -sd+ | bc ; ) \
                <(grep 'open files\|processes\|pending signals' /proc/self/limits | cut -c1-19) | \
          while read a b name ; do echo $((${b}00/a))% $name ; done

          
          
  build2:
    runs-on: ubuntu-latest

    steps:
      - run: ulimit -n
      - run: ulimit -u
      - run: ulimit -i
      - run: |
          paste <(grep 'open files\|processes\|pending signals' \
                        /proc/self/limits | cut -c27-38)        \
                <(i=`whoami`
                  lsof -n -u $i 2> /dev/null | 
                       tail -n +2 | 
                       awk {'print $9'} | 
                       wc -l
                  ps --no-headers -U $i -u $i u | wc -l
                  ps -u $i -o pid= | 
                       xargs printf "/proc/%s/status\n" |
                       xargs grep -s 'SigPnd' |
                       sed 's/.*\t//' | 
                       paste -sd+ | 
                       bc ; ) \
                <(grep 'open files\|processes\|pending signals' \
                       /proc/self/limits | 
                             cut -c1-19) | 
          while read a b name ; do 
              printf '%3i%%  %s\n' $((${b}00/a)) "$name"
          done
